name: Run Daily Intercom Count

on:
  schedule:
    # This schedule runs the job at 01:00 UTC every day.
    # You can adjust the time as needed. Use https://crontab.guru/ for help.
    - cron: '0 1 * * *'
  
  # This allows you to run the workflow manually from the Actions tab on GitHub.
  # This is useful for testing and on-demand runs.
  workflow_dispatch:

jobs:
  run-intercom-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the user counting and tagging script
        run: python ./count_intercom_users.py 1 --tag
        env:
          INTERCOM_TOKEN: ${{ secrets.INTERCOM_TOKEN }}
          CODA_WEBHOOK_URL: ${{ secrets.CODA_WEBHOOK_URL }}
          CODA_API_TOKEN: ${{ secrets.CODA_API_TOKEN }} 